# Generate kernels_embedded.h from .cl files in kernels/
$kernels = Get-ChildItem -Path kernels -Filter *.cl
$headerPath = "light/kernels_embedded.h"

$headerContent = @"
/* This file is automatically generated by stringify_kernels.ps1 */
#ifndef KERNELS_EMBEDDED_H
#define KERNELS_EMBEDDED_H

"@

foreach ($file in $kernels) {
    $varName = "kernel_source_" + $file.BaseName
    $content = Get-Content -Path $file.FullName -Raw
    
    # Escape backslashes and quotes
    $escapedContent = $content.Replace('\', '\\').Replace('"', '\"').Replace("`r`n", "\n").Replace("`n", "\n")
    
    # Split into lines to avoid extremely long string literals that some compilers dislike
    $lines = $escapedContent -split "\n"
    $formattedLines = ""
    foreach ($line in $lines) {
        $formattedLines += "    `"$line\n`"`r`n"
    }
    
    $headerContent += "const char *$varName = `r`n$formattedLines;`r`n`r`n"
}

$headerContent += "#endif`r`n"

$headerContent | Set-Content -Path $headerPath -Encoding UTF8
Write-Host "Generated $headerPath with $($kernels.Count) kernels."
