#!/bin/bash

# Generate kernels_embedded.h from .cl files in makebspdata/kernels/
headerPath="light/kernels_embedded.h"

echo "/* This file is automatically generated by stringify_kernels.sh */" > "$headerPath"
echo "#ifndef KERNELS_EMBEDDED_H" >> "$headerPath"
echo "#define KERNELS_EMBEDDED_H" >> "$headerPath"
echo "" >> "$headerPath"

for file in makebspdata/kernels/*.cl; do
    filename=$(basename "$file")
    basename="${filename%.*}"
    varName="kernel_source_$basename"
    
    echo "const char *$varName =" >> "$headerPath"
    
    # Use sed to escape backslashes and quotes, and wrap each line in quotes
    # The 's/\\/\\\\/g' escapes backslashes
    # The 's/"/\\"/g' escapes quotes
    # The 's/.*/    "&\\n"/' wraps the line and adds a newline char
    sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/.*/    "&\\n"/' "$file" >> "$headerPath"
    
    echo ";" >> "$headerPath"
    echo "" >> "$headerPath"
done

echo "#endif" >> "$headerPath"

echo "Generated $headerPath"
